# Generated by Django 5.2.4 on 2025-07-05 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_backend', '0006_remove_product_in_stock_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
